### PR TITLE
Issue 71 - Review drop files in the file uploader

### LINKED ISSUE #71: Cross-site file uploads not working
To reproduce it do the following:

* open two browser windows side by side; in one, a Plone site with this package installed and the upload modal open; in the other, any web page with an image on it
* drag the image from the second page and drop into the upload modal; nothing happens

Fixing this should not break the standard local drag & drop functionality.

Refs. https://github.com/collective/collective.upload/issues/5

### PR DESCRIPTION
**Pull request by rodfersou**
closes #71

### CODE REVIEW

**Comment by rodfersou** [comment]
Until now I review file upload, remove one view, and it still works with firefox, but not on chrome

File: src/collective/upload/static/main.js [hunk 1]
```diff
@@ -186,32 +83,42 @@ $(document).ready(function() {
...
-                    });
+              e.preventDefault();
+              var upload_image = function(img) {
+                var canvas = document.createElement('canvas');
+                canvas.width = img.width;
+                canvas.height = img.height;
+                canvas.getContext('2d').drawImage(img, 0, 0, img.width, img.height);
+                canvas.toBlob(function (blob) {
+                  $('#fileupload').fileupload('add', {files: [blob]});
+                }, "image/jpeg");
```
Comment (hvelarde) [inline src/collective/upload/static/main.js]: why to hard-code a mime type? this could lead to false positives on images

File: src/collective/upload/static/main.js [hunk 2]
```diff
@@ -186,32 +83,42 @@ $(document).ready(function() {
...
                 }
-                e.preventDefault();
+                reader.readAsBinaryString(file);
+              }
+              // drop one file from other site
+              var url = $('img', e.originalEvent.dataTransfer.getData('text/html')).attr('src');
+              if (url) {
+                $.getImageData({
+                  url: url,
+                  server:'http://localhost:8080/Plone/@@jsonimageserializer?callback=?',
```
Comment (hvelarde) [inline src/collective/upload/static/main.js]: why to hard-code a server on `localhost:8080`? this is the cause of weird messages sometimes appearing in the folder contents view.

File: src/collective/upload/static/main.js (hunk 1 above)
Comment (rodfersou) [inline src/collective/upload/static/main.js]: this is just do fill the canvas preview, the original image is not hard-coded type

File: src/collective/upload/static/main.js (hunk 2 above)
Comment (rodfersou) [inline src/collective/upload/static/main.js]: good question.. I just copied what was already there without read.. I'm going to fix it

File: src/collective/upload/static/main.js (hunk 1 above)
Comment (hvelarde) [inline src/collective/upload/static/main.js]: why not use the real mime type then?

Comment (rodfersou) [inline src/collective/upload/static/main.js]: I don't know, I borrowed this part of the code from jquery fileupload docs, but I can try to get the image mime type

**Comment by hvelarde** [comment]
@rodfersou I'm going to merge this but an upgrade step to cook JavaScript resources is still missing.
